/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerenciadorInterGrafica;
import controller.TMListagemBoards;
import domain.Board;
import domain.Usuario;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author 2023122760093
 */
public class BoardsDlg extends javax.swing.JDialog {

    private TMListagemBoards tmListagemBoards;
    private GerenciadorInterGrafica gerGrafica = GerenciadorInterGrafica.getMyInstance();
    private java.awt.Frame parent = null;

    /**
     * Creates new form Boards
     */
    public BoardsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Amarro o JTable com o meu Abstract Table Model
        tmListagemBoards = new TMListagemBoards();
        table.setModel(tmListagemBoards);
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaListagemBoardPopupMenu = new javax.swing.JPopupMenu();
        irParaTarefasMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        usuariosComboBox = new javax.swing.JComboBox<>();
        pesquisaLable = new javax.swing.JLabel();
        pesquisaTextField = new javax.swing.JTextField();

        irParaTarefasMenuItem.setText("Ir para tarefas");
        irParaTarefasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irParaTarefasMenuItemActionPerformed(evt);
            }
        });
        tabelaListagemBoardPopupMenu.add(irParaTarefasMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem de boards por usuário"));

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Id", "Nome", "Descrição", "Proprietário", "Status"
                }));
        table.setComponentPopupMenu(tabelaListagemBoardPopupMenu);
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanelLayout.setVerticalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 10, Short.MAX_VALUE)));

        usuariosComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariosComboBoxActionPerformed(evt);
            }
        });

        pesquisaLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/search.png"))); // NOI18N
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseExited(evt);
            }
        });

        pesquisaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(pesquisaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pesquisaLable)
                                .addGap(18, 18, 18)
                                .addComponent(usuariosComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(jPanel3Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(usuariosComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 25,
                                                Short.MAX_VALUE)
                                        .addComponent(pesquisaLable, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(pesquisaTextField))
                                .addContainerGap(18, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        gerGrafica.loadCombo(usuariosComboBox, Usuario.class);
    }// GEN-LAST:event_formComponentShown

    private void usuariosComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_usuariosComboBoxActionPerformed

        Usuario usuario = (Usuario) usuariosComboBox.getSelectedItem();
        List<Board> listaBoards = gerGrafica.getGerenciadorDominio().listarBoardsPorUsuario(usuario.getId());
        this.tmListagemBoards.setLista(null);

        this.tmListagemBoards.setLista(listaBoards);
    }// GEN-LAST:event_usuariosComboBoxActionPerformed

    private void irParaTarefasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_irParaTarefasMenuItemActionPerformed
        ArrayList<Board> list = (ArrayList<Board>) tmListagemBoards.getLista();
        Board item = (Board) /* list.stream().filter(obj -> obj.equals( */tmListagemBoards
                .getItem(table.getSelectedRow())/* )).findFirst(); */;
        dispose();
        gerGrafica.openTasksDlgFromDlg(list, item, this.parent);

    }// GEN-LAST:event_irParaTarefasMenuItemActionPerformed

    private void pesquisaLableMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseEntered
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.setBackground(Color.DARK_GRAY);
    }// GEN-LAST:event_pesquisaLableMouseEntered

    private void pesquisaLableMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseExited
        pesquisaLable.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
    }// GEN-LAST:event_pesquisaLableMouseExited

    private void pesquisaLableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseClicked
        atualizarCombo();

    }// GEN-LAST:event_pesquisaLableMouseClicked

    private void pesquisaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_pesquisaTextFieldKeyReleased
        atualizarCombo();
    }// GEN-LAST:event_pesquisaTextFieldKeyReleased

    
    private void atualizarCombo(){
        String pesq = pesquisaTextField.getText();
        List<Usuario> listaUsuarios = gerGrafica.getGerenciadorDominio().pesquisarUsuariosPorNome(pesq);
        
        if(listaUsuarios.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum correspondência com a pesquisa.", "Sem correspondência", JOptionPane.INFORMATION_MESSAGE);
            pesquisaTextField.setText("");
            return;
        }
        usuariosComboBox.setModel(new DefaultComboBoxModel(listaUsuarios.toArray()));    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BoardsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BoardsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BoardsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BoardsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BoardsDlg dialog = new BoardsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem irParaTarefasMenuItem;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pesquisaLable;
    private javax.swing.JTextField pesquisaTextField;
    private javax.swing.JPopupMenu tabelaListagemBoardPopupMenu;
    private javax.swing.JTable table;
    private javax.swing.JComboBox<String> usuariosComboBox;
    // End of variables declaration//GEN-END:variables
}
