/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package viewer;

import controller.GerenciadorInterGrafica;
import controller.TMBoard;
import domain.Board;
import domain.Proprietario;
import domain.Usuario;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class BoardRegisterDlg extends javax.swing.JDialog {
    //private DefaultTableModel boardDefaultTable;
    private List<Board> boardList = new ArrayList<>();
    private String statusRepository[] = {"active", "unactive"};
    private TMBoard tmBoard;

    /**
     * Creates new form BoardRegisterDlg
     */
    public BoardRegisterDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //setBoardTable();
        // Amarro o JTable com o meu Abstract Table Model
        tmBoard = new TMBoard();
        boardsTable.setModel(tmBoard);
        
        for (Object boardObj : GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().listar(Board.class)) {
            Board board = (Board) boardObj;
            this.tmBoard.adicionar(board);
        }
        GerenciadorInterGrafica gerGrafica = GerenciadorInterGrafica.getMyInstance();
        List<Object> usuarioList =  gerGrafica.getGerenciadorDominio().listar(Usuario.class);
        Object usuarioArray[] = new Usuario[usuarioList.size()];
        int i = 0;
        for(Object usuarioObj : usuarioList){
            Usuario usuario = (Usuario) usuarioObj;
            usuarioArray[i] = usuario;
            i++;
        }
        //ownerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(userArray));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { statusRepository[0], statusRepository[1] }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        boardTablePopupMenu = new javax.swing.JPopupMenu();
        clearMenuItem = new javax.swing.JMenuItem();
        editarMenuItem = new javax.swing.JMenuItem();
        cadastrarMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        newBoardText = new javax.swing.JTextField();
        addBoardButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        descriptionTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ownerComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        boardsTable = new javax.swing.JTable();

        boardTablePopupMenu.setComponentPopupMenu(boardTablePopupMenu);

        clearMenuItem.setText("clear");
        clearMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMenuItemActionPerformed(evt);
            }
        });
        boardTablePopupMenu.add(clearMenuItem);

        editarMenuItem.setText("edit");
        boardTablePopupMenu.add(editarMenuItem);

        cadastrarMenuItem.setText("cadastrar");
        cadastrarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarMenuItemActionPerformed(evt);
                addBoardButtonActionPerformed(evt);
            }
        });
        boardTablePopupMenu.add(cadastrarMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Register a new Board"));

        jLabel1.setText("Name");

        newBoardText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBoardTextActionPerformed(evt);
            }
        });

        addBoardButton.setText("Add");
        addBoardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBoardButtonMouseClicked(evt);
            }
        });
        addBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBoardButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Description");

        jLabel3.setText("Owner");

        ownerComboBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ownerComboBoxMouseClicked(evt);
            }
        });
        ownerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerComboBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Status");

        statusComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusComboBoxActionPerformed(evt);
            }
        });

        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newBoardText)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ownerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(83, 83, 83)
                .addComponent(addBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(newBoardText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ownerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(descriptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBoardButton)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 462, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Board list"));
        jPanel2.setLayout(new java.awt.BorderLayout());

        boardsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nome", "Descrição", "Proprietário", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        boardsTable.setComponentPopupMenu(boardTablePopupMenu);
        jScrollPane1.setViewportView(boardsTable);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 164, -1, 179));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newBoardTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBoardTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBoardTextActionPerformed

    private void addBoardButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBoardButtonMouseClicked
        
    }//GEN-LAST:event_addBoardButtonMouseClicked

    private void addBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBoardButtonActionPerformed
        Boolean status;
        System.out.println("COMBOX:"+statusComboBox.getSelectedItem().toString());
        if(statusComboBox.getSelectedItem().toString().equals("active")){
            status = true;
        }else{
            status = false;
        }
        
        Board novoBoard = Board.builder().descricao(descriptionTextField.getText())
                .nome(newBoardText.getText())
                .proprietario((Proprietario)ownerComboBox.getSelectedItem())
                .status(status)
                .build();
        GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().criar(novoBoard);
        this.boardList.add(novoBoard);
        
        newBoardText.setText("");
        descriptionTextField.setText("");
        ownerComboBox.setSelectedIndex(0);
        statusComboBox.setSelectedIndex(0);
        
        this.tmBoard.adicionar(novoBoard);
        
    }//GEN-LAST:event_addBoardButtonActionPerformed

    private void ownerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerComboBoxActionPerformed

    }//GEN-LAST:event_ownerComboBoxActionPerformed

    private void ownerComboBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerComboBoxMouseClicked

         // TODO add your handling code here:
    }//GEN-LAST:event_ownerComboBoxMouseClicked

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusComboBoxActionPerformed

    private void cadastrarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastrarMenuItemActionPerformed

    private void clearMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMenuItemActionPerformed
        int linha = boardsTable.getSelectedRow();
        if(linha >= 0){
            if(JOptionPane.showConfirmDialog(this, "Delete it?") == JOptionPane.YES_OPTION){
            Board board = (Board)(this.tmBoard).getItem(linha);
            (this.tmBoard).remover(linha);
            GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().deletar(board);        
            }

        }
    }//GEN-LAST:event_clearMenuItemActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        GerenciadorInterGrafica.getMyInstance().loadCombo(ownerComboBox, Usuario.class);
        
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /*private void setBoardTable() {
        this.boardDefaultTable = (DefaultTableModel) boardsTable.getModel();
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBoardButton;
    private javax.swing.JPopupMenu boardTablePopupMenu;
    private javax.swing.JTable boardsTable;
    private javax.swing.JMenuItem cadastrarMenuItem;
    private javax.swing.JMenuItem clearMenuItem;
    private javax.swing.JTextField descriptionTextField;
    private javax.swing.JMenuItem editarMenuItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField newBoardText;
    private javax.swing.JComboBox<String> ownerComboBox;
    private javax.swing.JComboBox<String> statusComboBox;
    // End of variables declaration//GEN-END:variables
}
