package viewer;


import controller.GerenciadorInterGrafica;
import domain.Board;
import domain.Tarefa;
import domain.Usuario;
import infrastructure.IBoardRepository;
import infrastructure.IBoardRepositoryImpl;
import infrastructure.IUserRepository;
import infrastructure.IUserRepositoryImpl;
import service.BoardService;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {   

    /**
     * Creates new form FrmPrincipal
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UserRegisterMenuItem = new javax.swing.JMenuItem();
        taskRegisterMenuItem = new javax.swing.JMenuItem();
        boardRegisterMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        listarBoardPorUsuario = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        listagemTarefasPorBoard = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setLocation(new java.awt.Point(700, 300));
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/taskManagerFrase.png"))); // NOI18N
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastro");

        UserRegisterMenuItem.setText("User");
        UserRegisterMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserRegisterMenuItemMouseClicked(evt);
            }
        });
        UserRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(UserRegisterMenuItem);

        taskRegisterMenuItem.setText("Task");
        taskRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(taskRegisterMenuItem);

        boardRegisterMenuItem.setText("Board");
        boardRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(boardRegisterMenuItem);
        jMenu1.add(jSeparator1);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Boards");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        listarBoardPorUsuario.setText("Listar boards por usuário");
        listarBoardPorUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBoardPorUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(listarBoardPorUsuario);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        listagemTarefasPorBoard.setText("Listagem de tarefas por board");
        listagemTarefasPorBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemTarefasPorBoardActionPerformed(evt);
            }
        });
        jMenu3.add(listagemTarefasPorBoard);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reports");

        jMenuItem1.setText("display");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegisterMenuItemActionPerformed
        GerenciadorInterGrafica.getMyInstance().openClientRegisterDlg();
    }//GEN-LAST:event_UserRegisterMenuItemActionPerformed

    private void UserRegisterMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRegisterMenuItemMouseClicked

    }//GEN-LAST:event_UserRegisterMenuItemMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void taskRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskRegisterMenuItemActionPerformed
        List<Object> boards = GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().listar(Board.class);
        if(boards.isEmpty()){
            JOptionPane.showMessageDialog(this, "At least one board must to be registered.", "No board registered", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        GerenciadorInterGrafica.getMyInstance().openTaskRegisterDlg();        
    }//GEN-LAST:event_taskRegisterMenuItemActionPerformed

    private void boardRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardRegisterMenuItemActionPerformed
        List<Object> users = GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().listar(Usuario.class);
        if(users.isEmpty()){
            JOptionPane.showMessageDialog(this, "At least one user must to be registered.", "No user registered", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        GerenciadorInterGrafica.getMyInstance().openBoardRegisterDlg();
    }//GEN-LAST:event_boardRegisterMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        GerenciadorInterGrafica.getMyInstance().exit();
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    private void listarBoardPorUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBoardPorUsuarioActionPerformed
        GerenciadorInterGrafica.getMyInstance().openBoardsDlg();
    }//GEN-LAST:event_listarBoardPorUsuarioActionPerformed

    private void listagemTarefasPorBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemTarefasPorBoardActionPerformed
        GerenciadorInterGrafica.getMyInstance().openTasksDlgFromFrm();
    }//GEN-LAST:event_listagemTarefasPorBoardActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        List list = GerenciadorInterGrafica.getMyInstance().getGerenciadorDominio().listar(Tarefa.class);
        
        GerenciadorInterGrafica.getMyInstance().getGerenciadorRelatorios().relComLista(list, "tarefas_criadas.jasper");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {*/
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         /*
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem UserRegisterMenuItem;
    private javax.swing.JMenuItem boardRegisterMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem listagemTarefasPorBoard;
    private javax.swing.JMenuItem listarBoardPorUsuario;
    private javax.swing.JMenuItem taskRegisterMenuItem;
    // End of variables declaration//GEN-END:variables
}
