package viewer;


import Domain.Board;
import Domain.User;
import Infrastructure.IBoardRepository;
import Infrastructure.IBoardRepositoryImpl;
import Infrastructure.IUserRepository;
import Infrastructure.IUserRepositoryImpl;
import controller.GraphicInterfaceManager;
import service.BoardService;
import service.UserService;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class MainFrame extends javax.swing.JFrame {   

    /**
     * Creates new form FrmPrincipal
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        UserRegisterMenuItem = new javax.swing.JMenuItem();
        taskRegisterMenuItem = new javax.swing.JMenuItem();
        boardRegisterMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        boardMenu = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Início");
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/taskManagerFrase.png"))); // NOI18N
        getContentPane().add(jLabel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Cadastro");

        UserRegisterMenuItem.setText("User");
        UserRegisterMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserRegisterMenuItemMouseClicked(evt);
            }
        });
        UserRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(UserRegisterMenuItem);

        taskRegisterMenuItem.setText("Task");
        taskRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(taskRegisterMenuItem);

        boardRegisterMenuItem.setText("Board");
        boardRegisterMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardRegisterMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(boardRegisterMenuItem);
        jMenu1.add(jSeparator1);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(ExitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Boards");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        boardMenu.setText("Boards");
        boardMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boardMenuMouseClicked(evt);
            }
        });
        boardMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardMenuActionPerformed(evt);
            }
        });
        jMenu2.add(boardMenu);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Reports");

        jMenu5.setText("display");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Mais recentes");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jRadioButtonMenuItem1);

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Antigos");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jRadioButtonMenuItem2);

        jMenu4.add(jMenu5);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRegisterMenuItemActionPerformed
        GraphicInterfaceManager.getMyInstance().openClientRegisterDlg();
    }//GEN-LAST:event_UserRegisterMenuItemActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void UserRegisterMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserRegisterMenuItemMouseClicked

    }//GEN-LAST:event_UserRegisterMenuItemMouseClicked

    private void boardMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardMenuActionPerformed

    }//GEN-LAST:event_boardMenuActionPerformed

    private void boardMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boardMenuMouseClicked

    }//GEN-LAST:event_boardMenuMouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked

    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void taskRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_taskRegisterMenuItemActionPerformed
        List<Board> boards = GraphicInterfaceManager.getMyInstance().loadBoards();
        if(boards.isEmpty()){
            JOptionPane.showMessageDialog(this, "At least one board must to be registered.", "No board registered", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        GraphicInterfaceManager.getMyInstance().openTaskRegisterDlg();        
    }//GEN-LAST:event_taskRegisterMenuItemActionPerformed

    private void boardRegisterMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardRegisterMenuItemActionPerformed
        List<User> users = GraphicInterfaceManager.getMyInstance().loadUsers();
        if(users.isEmpty()){
            JOptionPane.showMessageDialog(this, "At least one user must to be registered.", "No user registered", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        GraphicInterfaceManager.getMyInstance().openBoardRegisterDlg();
    }//GEN-LAST:event_boardRegisterMenuItemActionPerformed

    private void ExitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItemActionPerformed
        GraphicInterfaceManager.getMyInstance().exit();
    }//GEN-LAST:event_ExitMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    
    /*public static void main(String args[]) {*/
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         /*
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        */
        //</editor-fold>
        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem UserRegisterMenuItem;
    private javax.swing.JMenu boardMenu;
    private javax.swing.JMenuItem boardRegisterMenuItem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem taskRegisterMenuItem;
    // End of variables declaration//GEN-END:variables
}
