package viewer;

import controller.GerenciadorInterGrafica;
import controller.TMListagemBoards;
import controller.TMListagemTarefas;
import domain.Board;
import domain.Tarefa;
import domain.Usuario;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author Usuário
 */
public class TasksDlg extends javax.swing.JDialog {

    private TMListagemTarefas tmListagemTarefas;
    private GerenciadorInterGrafica gerGrafica = GerenciadorInterGrafica.getMyInstance();
    private java.awt.Frame parent;

    /**
     * Creates new form NewJDialog
     */
    public TasksDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        amarrarAbstractTableModel();
        
        this.parent = parent;

        // tarefasJTable.setShowGrid(true); // Exibe a grade
        // tarefasJTable.setGridColor(Color.BLACK); // Define a cor da grade

    }

    public TasksDlg(Frame parent, boolean modal, List list, Object selectedComboItem) {
        super(parent, modal);
        initComponents();

        amarrarAbstractTableModel();
        boardsComboBox.setModel(new DefaultComboBoxModel(list.toArray()));

        boardsComboBox.setSelectedItem(selectedComboItem);

        this.parent = parent;

    }

    private void amarrarAbstractTableModel() {
        tmListagemTarefas = new TMListagemTarefas();
        table.setModel(tmListagemTarefas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabelaListagemTarefaPopupMenu = new javax.swing.JPopupMenu();
        irParaTarefaMenuItem = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        boardsComboBox = new javax.swing.JComboBox<>();
        pesquisaLable = new javax.swing.JLabel();
        pesquisaTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        irParaTarefaMenuItem.setText("Ir para tarefa");
        irParaTarefaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irParaTarefaMenuItemActionPerformed(evt);
            }
        });
        tabelaListagemTarefaPopupMenu.add(irParaTarefaMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Listagem de tarefas por board"));

        boardsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardsComboBoxActionPerformed(evt);
            }
        });

        pesquisaLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/search.png"))); // NOI18N
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseExited(evt);
            }
        });

        pesquisaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(pesquisaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(pesquisaLable)
                                .addGap(18, 18, 18)
                                .addComponent(boardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 261,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(pesquisaTextField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(boardsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pesquisaLable))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tarefas"));

        table.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Id", "Nome", "Responsável", "Prioridade", "Fase", "Vencimento"
                }));
        table.setComponentPopupMenu(tabelaListagemTarefaPopupMenu);
        jScrollPane2.setViewportView(table);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        gerGrafica.loadCombo(boardsComboBox, Board.class);
    }// GEN-LAST:event_formComponentShown

    private void pesquisaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_pesquisaTextFieldKeyReleased
        atualizarCombo();
    }// GEN-LAST:event_pesquisaTextFieldKeyReleased

    private void pesquisaLableMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseClicked
        atualizarCombo();
    }// GEN-LAST:event_pesquisaLableMouseClicked

    private void irParaTarefaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_irParaTarefaMenuItemActionPerformed
        ArrayList<Tarefa> list = (ArrayList<Tarefa>) tmListagemTarefas.getLista();
        Tarefa item = (Tarefa) /* list.stream().filter(obj -> obj.equals( */tmListagemTarefas
                .getItem(table.getSelectedRow())/* )).findFirst(); */;
        dispose();
        gerGrafica.openTarefaDlg(list, item, this.parent);
    }// GEN-LAST:event_irParaTarefaMenuItemActionPerformed

    private void boardsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boardsComboBoxActionPerformed
        Board board = (Board) boardsComboBox.getSelectedItem();
        List<Tarefa> listaTarefas = gerGrafica.getGerenciadorDominio().listarTarefasPorBoard(board.getId());
        this.tmListagemTarefas.setLista(null);

        this.tmListagemTarefas.setLista(listaTarefas);
    }// GEN-LAST:event_boardsComboBoxActionPerformed

    private void pesquisaLableMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseEntered
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.setBackground(Color.DARK_GRAY);
    }// GEN-LAST:event_pesquisaLableMouseEntered

    private void pesquisaLableMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseExited
        pesquisaLable.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
    }// GEN-LAST:event_pesquisaLableMouseExited
    private void atualizarCombo(){
        String pesq = pesquisaTextField.getText();
        List<Board> listaBoards = gerGrafica.getGerenciadorDominio().pesquisarBoardsPorNome(pesq);
        
        if(listaBoards.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum correspondência com a pesquisa.", "Sem correspondência", JOptionPane.INFORMATION_MESSAGE);
            pesquisaTextField.setText("");
            return;
        }
        boardsComboBox.setModel(new DefaultComboBoxModel(listaBoards.toArray()));    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TasksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TasksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TasksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TasksDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TasksDlg dialog = new TasksDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boardsComboBox;
    private javax.swing.JMenuItem irParaTarefaMenuItem;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pesquisaLable;
    private javax.swing.JTextField pesquisaTextField;
    private javax.swing.JPopupMenu tabelaListagemTarefaPopupMenu;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
