package viewer;

import controller.GerenciadorInterGrafica;
import domain.Board;
import domain.Categoria;
import domain.Tarefa;
import domain.Usuario;
import java.awt.Color;
import java.awt.Frame;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
/**
 *
 * @author Usuario
 */
public class TaskRegisterDlg extends javax.swing.JDialog {

    private GerenciadorInterGrafica gerGrafica = GerenciadorInterGrafica.getMyInstance();

    /**
     * Creates new form TaskRegisterDlg
     *
     * @param parent
     * @param modal
     */
    public TaskRegisterDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    public TaskRegisterDlg(Frame parent, boolean modal, Tarefa obj) {
        super(parent, modal);
        initComponents();

        atualizarCampos(obj);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        taskNameTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        taskResponsibleComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        taskPriorityComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        upstreamPhaseComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionText = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        boradComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        categoriaComboBox = new javax.swing.JComboBox<>();
        dateChooser = new com.toedter.calendar.JDateChooser();
        cancelButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        pesquisaTextField = new javax.swing.JTextField();
        pesquisaLable = new javax.swing.JLabel();
        tarefasComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setText("Nome");

        taskNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taskNameTxtActionPerformed(evt);
            }
        });

        jLabel2.setText("Responsável");

        taskResponsibleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select" }));

        jLabel3.setText("Prioridade");

        taskPriorityComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "low", "medium", "High", " " }));

        jLabel5.setText("Fase");

        upstreamPhaseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "Ready for sprint", "Not approved", " " }));

        jLabel6.setText("Vencimento");

        descriptionText.setColumns(20);
        descriptionText.setRows(5);
        descriptionText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(102, 102, 102))); // NOI18N
        jScrollPane1.setViewportView(descriptionText);

        jLabel7.setText("Board");

        boradComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boradComboBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Categoria");

        categoriaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        categoriaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taskResponsibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(taskNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(boradComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(taskPriorityComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(73, 73, 73)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(upstreamPhaseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(categoriaComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskResponsibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskPriorityComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(categoriaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(upstreamPhaseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(boradComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        createButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/accept.png"))); // NOI18N
        createButton.setText("Salvar");
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
        });
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));

        pesquisaTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaTextFieldKeyReleased(evt);
            }
        });

        pesquisaLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/png/16x16/search.png"))); // NOI18N
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pesquisaLableMouseExited(evt);
            }
        });

        tarefasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarefasComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pesquisaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(pesquisaLable)
                .addGap(26, 26, 26)
                .addComponent(tarefasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesquisaLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tarefasComboBox)
                    .addComponent(pesquisaTextField))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(createButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pesquisaTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaTextFieldKeyReleased
        atualizarCombo();
    }//GEN-LAST:event_pesquisaTextFieldKeyReleased

    private void pesquisaLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pesquisaLableMouseClicked
        atualizarCombo();
    }//GEN-LAST:event_pesquisaLableMouseClicked

    private void tarefasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarefasComboBoxActionPerformed
        Tarefa tarefaSelecionada = (Tarefa) tarefasComboBox.getSelectedItem();

        atualizarCampos(tarefaSelecionada);
    }//GEN-LAST:event_tarefasComboBoxActionPerformed

    private void taskNameTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_taskNameTxtActionPerformed

    }// GEN-LAST:event_taskNameTxtActionPerformed

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_createButtonMouseClicked

    }// GEN-LAST:event_createButtonMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {// GEN-FIRST:event_formComponentShown
        Tarefa tarefaVazia = new Tarefa();
        atualizarCampos(tarefaVazia);

        carregarCombos();

    }// GEN-LAST:event_formComponentShown

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
        Tarefa tarefaVazia = new Tarefa();
        atualizarCampos(tarefaVazia);

        /*taskNameTxt.setText("");
        taskResponsibleComboBox.setSelectedIndex(0);
        taskPriorityComboBox.setSelectedIndex(0);
        boradComboBox.setSelectedIndex(0);
        categoriaComboBox.setSelectedItem(0);
        dateChooser.setDate(null);
        upstreamPhaseComboBox.setSelectedIndex(0);
        descriptionText.setText("");*/
        dispose();
    }// GEN-LAST:event_cancelButtonActionPerformed

    private void boradComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_boradComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_boradComboBoxActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_createButtonActionPerformed

        Date data = dateChooser.getDate();

        Tarefa tarefa = Tarefa.builder().build();
        tarefa.setNome(taskNameTxt.getText());
        tarefa.setResponsavel((Usuario) taskResponsibleComboBox.getSelectedItem());
        tarefa.setPrioridade((String) taskPriorityComboBox.getSelectedItem());
        tarefa.setBoard((Board) boradComboBox.getSelectedItem());
        tarefa.setCategoria((Categoria) categoriaComboBox.getSelectedItem());
        tarefa.setDataVencimento(data);
        tarefa.setFase((String) upstreamPhaseComboBox.getSelectedItem());
        tarefa.setDescricao(descriptionText.getText());

        gerGrafica.getGerenciadorDominio().criar(tarefa);
        Tarefa tarefaVazia = new Tarefa();
        atualizarCampos(tarefaVazia);

        /*taskNameTxt.setText("");
        taskResponsibleComboBox.setSelectedIndex(0);
        taskPriorityComboBox.setSelectedIndex(0);
        boradComboBox.setSelectedIndex(0);
        categoriaComboBox.setSelectedItem(0);
        dateChooser.setDate(null);
        upstreamPhaseComboBox.setSelectedIndex(0);
        descriptionText.setText("");*/
    }// GEN-LAST:event_createButtonActionPerformed

    private void categoriaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_categoriaComboBoxActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_categoriaComboBoxActionPerformed

    private void pesquisaLableMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseEntered
        pesquisaLable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pesquisaLable.setBackground(Color.DARK_GRAY);

    }// GEN-LAST:event_pesquisaLableMouseEntered

    private void pesquisaLableMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_pesquisaLableMouseExited
        pesquisaLable.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
    }// GEN-LAST:event_pesquisaLableMouseExited

    private void atualizarCombo() {
        String pesq = pesquisaTextField.getText();
        List<Tarefa> listaTarefas = gerGrafica.getGerenciadorDominio().pesquisarTarefasPorNome(pesq);

        if (listaTarefas.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum correspondência com a pesquisa.", "Sem correspondência", JOptionPane.INFORMATION_MESSAGE);
            pesquisaTextField.setText("");
            Tarefa tarefaVazia = new Tarefa();
            atualizarCampos(tarefaVazia);
            carregarCombos();
            return;
        }
        tarefasComboBox.setModel(new DefaultComboBoxModel(listaTarefas.toArray()));
    }

    private void atualizarCampos(Tarefa tarefa) {
        taskNameTxt.setText(tarefa.getNome());
        taskResponsibleComboBox.setSelectedItem(tarefa.getResponsavel());
        taskPriorityComboBox.setSelectedItem(tarefa.getPrioridade());
        boradComboBox.setSelectedItem(tarefa.getBoard());
        upstreamPhaseComboBox.setSelectedItem(tarefa.getFase());
        dateChooser.setDate(tarefa.getDataVencimento());
        categoriaComboBox.setSelectedItem(tarefa.getCategoria());
        descriptionText.setText(tarefa.getDescricao());
    }
    
    private void carregarCombos(){
        gerGrafica.loadCombo(taskResponsibleComboBox, Usuario.class);
        gerGrafica.loadCombo(boradComboBox, Board.class);
        gerGrafica.loadCombo(categoriaComboBox, Categoria.class);
        gerGrafica.loadCombo(tarefasComboBox, Tarefa.class);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskRegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskRegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskRegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskRegisterDlg.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskRegisterDlg dialog = new TaskRegisterDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boradComboBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JComboBox<String> categoriaComboBox;
    private javax.swing.JButton createButton;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JTextArea descriptionText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel pesquisaLable;
    private javax.swing.JTextField pesquisaTextField;
    private javax.swing.JComboBox<String> tarefasComboBox;
    private javax.swing.JTextField taskNameTxt;
    private javax.swing.JComboBox<String> taskPriorityComboBox;
    private javax.swing.JComboBox<String> taskResponsibleComboBox;
    private javax.swing.JComboBox<String> upstreamPhaseComboBox;
    // End of variables declaration//GEN-END:variables
}
